### PR TITLE
Boilerplate Cleanup

### LINKED ISSUE #44: Boilerplate cleanup
The code has a lot of boilerplate, and I'd like to reduce it some by making helper functions and such

For example:
* Every list generation from multiple fields is pretty much the exact same code
* All the version checks could be a function call to something like `minimum_accepted_version` and `maximum_accepted_version`
* A lot of `request.args.get` calls could be simplified (example below)

```python
if request.args.get('excludedetails') and request.args.get('excludedetails') == 'true'

# 'false' could be replaces with just '', or not be there at all, but this is clearer to what's happening
if request.args.get('excludedetails', 'false') == 'true'
```

I'd be willing to do any or all of these changes, just not sure which ones are wanted, so any feedback would be nice.

### PR DESCRIPTION
**Pull request by Micalobia**
Resolves #44, very open to changes, as none of this was talked about. Cuts down the file size of `app.py` by ~5%, as well as making the creation of new endpoints a lot easier.

### CODE REVIEW

**Comment by Micalobia** [comment]
Considering working on trying to reduce the clutter made by all the `where <condition>` statement building, as well as *maybe* simplifying cargo queries more, although that's a lesser concern.

**Comment by Micalobia** [comment]
I am not sure about the WhereBuilder commit, everything else I think is really beneficial though. Any feedback would be nice.

**Comment by Micalobia** [comment]
Should be good to go now, removed the `WhereBuilder` class for a much simpler, smaller helper function `params_where`, as well as making the way every `where` conditional was built the same.

**Review by KevinPayravi — APPROVED** [review]
Great stuff, thank you!

**Pull request merged**
